### ISSUE TITLE
Reduce CI notifications

### ISSUE THREAD

**Issue by raulriera** [Shopify/FunctionalTableData#45]
Travis is kind of noisy, update the yml with

```yml
notifications:
  email:
    on_success: never
    on_failure: always
```
